#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

############################################
# Install Ghost
############################################

dir=$PWD
export NVM_DIR=/opt/nvm && source /opt/nvm/nvm.sh
nvm use v18
if [[ ! $(which ghost) ]]; then
    npm install ghost-cli@latest -g
fi
if [ ! -d "/opt/ghost/versions" ]; then

    mkdir -p /opt/ghost
    if [ -d "/home/debian" ]; then
        chown debian:debian /opt/ghost
        runuser -l debian -c "export NVM_DIR=/opt/nvm && source /opt/nvm/nvm.sh && nvm use v18 && ghost install --dir /opt/ghost --no-prompt"
    fi
    if [ -d "/home/ubuntu" ]; then
        chown ubuntu:ubuntu /opt/ghost
        runuser -l ubuntu -c "export NVM_DIR=/opt/nvm && source /opt/nvm/nvm.sh && nvm use v18 && ghost install --dir /opt/ghost --no-prompt"
    fi
fi

# Copy over our Quick Install App
cd "$dir" || exit
rsync -r ./Installers/ /usr/local/hestia/web/src/app/WebApp/Installers/

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "Ghost" "&#128123; Ghost plugin has finished installing."
