#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

############################################
# Install Ghost
############################################

dir=$PWD
export NVM_DIR=/opt/nvm && source /opt/nvm/nvm.sh
nvm use v18
if [[ ! $(which ghost) ]]; then
    npm install ghost-cli@latest -g
fi

# Copy over our Quick Install App
cd "$dir" || exit
rsync -r ./Installers/ /usr/local/hestia/web/src/app/WebApp/Installers/

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "Ghost" "&#128123; Ghost plugin has finished installing."
