#!/bin/bash

############################################
# Uninstall Ghost
############################################
export NVM_DIR=/opt/nvm && source /opt/nvm/nvm.sh
nvm use v18
if [[ ! $(which ghost) ]]; then
    npm uninstall ghost-cli@latest -g
fi
